### ISSUE TITLE
Reseller index

### ISSUE THREAD

**Issue by joostdekeijzer** [smicroz/einDa-skin#15]
Hi smicroz,

Like the new version with the icons!

The reseller index is different than the others though, no icons.

Also, the "Edit User Message" button is broken.

I think this is because (only) this page is rendered using AngularJS and the EMU button is a javascript popup link Angular thinks is "unsafe".

**Comment by smicroz** [comment]
1. Now is reworked without angular
2. Works well now (with javascript)

Thanks
