### ISSUE TITLE
Missing custom fields.

### ISSUE THREAD

**Issue by ricardo777** [smicroz/einDa-skin#20]
Great skin.

After trying it out I see that there is no custom field in the skin yet.

Like Softaculous or Cloudlinux or DA skin selector.

**Comment by smicroz** [comment]
you mean customizing each one of these sections?

**Comment by ricardo777** [comment]
In /user/show_domain.html for example

you are missing the fields:

PLUGIN_0_TXT... etc.

So the Cloudlinux, Softaculous or Skin selector is not visible for me with your skin.

**Comment by smicroz** [comment]
Logged as administrator, should appear. I'll check 'reseller' and 'user' dashboard.

**Comment by smicroz** [comment]
They are added now. You must rerun the installer to update the skin.
