### ISSUE TITLE
Current Domain is none

### ISSUE THREAD

**Issue by drkt7** [smicroz/einDa-skin#26]
Hi!

in different page can be found : none (Current Domain)
![filemanager](https://cloud.githubusercontent.com/assets/12685775/7903242/9b94512e-07a3-11e5-8ba4-5c63852e0adf.png)
![protec_dir](https://cloud.githubusercontent.com/assets/12685775/7903243/9b955470-07a3-11e5-8ce7-19c26a4e76bd.png)
![question_sec](https://cloud.githubusercontent.com/assets/12685775/7903244/9b98b8e0-07a3-11e5-8b22-136a4afe3ab6.png)

**Comment by drkt7** [comment]
3 pages:
- Files Manager
- Protected Directories
- Security Questions
  ...

**Comment by smicroz** [comment]
Hi,

This happened because an account can have more than one domain, a possible solution would be to show all domains, or not show anything in these pages.

I will see....

**Comment by smicroz** [comment]
Well, now "Current domain" is hidden when you enter to these sections.
