### ISSUE TITLE
DNS Page

### ISSUE THREAD

**Issue by drkt7** [smicroz/einDa-skin#27]
Hi!

DNS page have problem...

if i have a "x._domainkey   TXT"

I do not see the check box to delete the record.

The domain name does not appear well .

![dkim](https://cloud.githubusercontent.com/assets/12685775/7903341/f6c902c6-07a6-11e5-913b-cb8d85badd7e.png)

**Comment by drkt7** [comment]
if you use Dkim: http://help.directadmin.com/item.php?id=569

**Comment by smicroz** [comment]
Thanks for reporting the issue. 

I'll update soon.

**Comment by drkt7** [comment]
DNS error is in USER account

Thanks!

**Comment by smicroz** [comment]
It was solved by guillermodejavu in https://github.com/smicroz/einDa-skin/commit/e24b0dcf5c6f9d571503917f35e380117f9fc28f

**Comment by drkt7** [comment]
i update skin, but i have same problem for DNS....

**Comment by drkt7** [comment]
is not this file... /admin/dns_admin.html
but is this file: /user/dns_control.html have error...
