### ISSUE TITLE
Missing services and system backup icons 

### ISSUE THREAD

**Issue by guillermodejavu** [smicroz/einDa-skin#29]
Both were removed in last commit for content_main.html

**Comment by guillermodejavu** [comment]
Correction this is the hash of the commit: 19f85abd960df982218c2cb06bc571c18fed22d6.

The system backup icon was moved upwards but the services was just removed.

**Comment by pawelpotoniec** [comment]
link to: CMD_SHOW_SERVICES is gone, why?

**Comment by smicroz** [comment]
Thanks for reporting, is solved. Try update.
