### ISSUE TITLE
2 factor authentication

### ISSUE THREAD

**Issue by maiweb** [smicroz/einDa-skin#30]
Hello!

Can you implement the 2 factor authentication in the templates?

http://www.directadmin.com/features.php?id=1754

Regards,

Maico

**Comment by smicroz** [comment]
Hi Maico,

2factor is available in latest version, Try update!

Rgds,
Eduardo

**Comment by maiweb** [comment]
Hi Eduardo,

Thnx!!!

Regards,

Maico
