### ISSUE TITLE
No download link for EinDa login

### ISSUE THREAD

**Issue by Web2Get** [smicroz/einDa-skin#31]
Dear Smicroz,

I really appreciate your work, I have changed our DA skin to the one you made but I feel like it's not complete yet as the inlog screen is still the old one.
I tried to find the download link for the login screen but I couldn't find it, is there any way you reupload it and give it to me?

**Comment by Web2Get** [comment]
I'm looking for a download link for this: http://smicroz.tumblr.com/post/104861076899/einda-login-for-directadmin

**Comment by smicroz** [comment]
Apparently link is broken, I will review this.

Thanks for notification.

**Comment by smicroz** [comment]
Now is included in Installer. Please try reinstall.

rm -f /usr/local/directadmin/data/skins/einDa-skin

then run installer instructions.
