### ISSUE TITLE
Filemanager icons

### ISSUE THREAD

**Issue by joostdekeijzer** [smicroz/einDa-skin#6]
Hi,

The filemanager icons are not available (404 errors). At least in Mac OS X Safari, you get "missing image" icons in the Filemanager screens. See attached screenshot.

In https://github.com/joostdekeijzer/einDa-skin/commit/bd93b9c204c170dc4f65e14ce7128a8266c8569c I've done some sort of fix keeping the text labels. There must be a better solution :-)

![screen shot 2015-01-12 at 11 18 49](https://cloud.githubusercontent.com/assets/216672/5701552/ef7e0916-9a4c-11e4-85d6-85716cacfb4f.png)

**Comment by joostdekeijzer** [comment]
Resolved with new version

**Comment by smicroz** [comment]
Thanks by update.
