### ISSUE TITLE
phpMyAdmin link

### ISSUE THREAD

**Issue by joostdekeijzer** [smicroz/einDa-skin#8]
Some phpMyAdmin links use `/pma`, others use `/phpmyadmin`.

I personally prefer `/phpmyadmin`, which is also what the enhanced skin uses.

Using `/pma`
admin/menu_admin.html
admin/menu_reseller.html
admin/menu_user.html
reseller/menu_reseller.html
reseller/menu_user.html
user/menu_user.html

Using `/phpmyadmin`
user/db/db.html
user/show_domain.html

**Comment by smicroz** [comment]
Good suggestion, now all link of phpmyadmin are htt.../phpmyadmin
